apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: portfolio-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: portfolio
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: portfolio
        minAllowed:
          cpu: 50m
          memory: 64Mi
        maxAllowed:
          cpu: 500m
          memory: 512Mi
        controlledResources: ["cpu", "memory"]
      - containerName: istio-proxy
        minAllowed:
          cpu: 25m
          memory: 64Mi
        maxAllowed:
          cpu: 250m
          memory: 256Mi
        controlledResources: ["cpu", "memory"]
